server: 
  port: 4024
  servlet:
    context-path: /app

spring: 
  application:
    name: todolist-redis
  cache:
    type: redis
  redis:
     cluster:
       nodes:
        - 172.20.0.3:6379
        - 172.20.0.2:6379
        - 172.20.0.4:6379
       maxRedirects: 2