server:
  port: 8080

spring:
  jpa:
    database: H2
    hibernate:
      # create - 생성한것 계속 쓰기
      ddl-auto: create
    show-sql: true
  datasource:
    # url접속시 jdbc:h2:mem:testdb 이걸 꼭 적어줘야 웹페이지로 DB정보를 볼 수 있다.
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2console